THEORITICAL QUES-

1. 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it 
   enhance Python's capabilities for numerical operations?

In NumPy, short for Numerical Python, is a powerful library in Python designed for numerical and scientific computing. It provides a high-performance multidimensional array object and tools for working with these arrays. Here’s how it enhances Python's capabilities for numerical operations and its advantages in scientific computing and data analysis:

Purpose of NumPy- 

Efficient Array Computation: NumPy introduces the ndarray (n-dimensional array), which allows efficient storage and manipulation of large datasets. Unlike Python lists, which are slow and consume more memory, NumPy arrays are optimized for performance.

Mathematical Functions: It includes a large collection of mathematical functions to operate on arrays, such as linear algebra operations, Fourier transforms, and random number generation.

Integration with Other Libraries: NumPy serves as the foundation for many other scientific libraries, such as SciPy, Pandas, and Matplotlib. These libraries rely on NumPy arrays for data storage and manipulation, making it a cornerstone of scientific computing in Python.

Advantages of NumPy-


Performance:

Vectorization: NumPy enables vectorized operations, meaning that operations can be applied to entire arrays at once without needing to write explicit loops in Python. This significantly speeds up computations.
C and Fortran Integration: NumPy is implemented in C and Fortran, allowing for execution speeds close to these low-level languages. This makes NumPy operations much faster than equivalent operations in pure Python.
Memory Efficiency:

Compact Data Storage: NumPy arrays are stored in contiguous blocks of memory, which reduces the overhead associated with storing large datasets. This leads to lower memory usage compared to Python lists.
Data Types: NumPy allows for the specification of data types for array elements, enabling more efficient storage and computation for large datasets.
Broad Functionality:

Broadcasting: This feature allows NumPy to perform operations on arrays of different shapes in a way that mimics the element-wise operations of arrays of the same shape.
Indexing and Slicing: NumPy provides powerful tools for array slicing, indexing, and reshaping, which are essential for data manipulation and analysis.

Enhancing Python’s Capabilities-

Python, by itself, is not optimized for high-performance numerical operations, especially when dealing with large datasets. NumPy enhances Python by providing:

Fast Execution: By replacing Python loops with NumPy operations, which are implemented in optimized C code.
Sophisticated Data Structures: NumPy arrays offer more powerful data structures compared to Python’s built-in data types, enabling complex mathematical and statistical operations.
Scalability: NumPy’s efficient use of memory and processing power allows Python to handle large-scale data analysis tasks that would be infeasible with native Python structures.

2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the 
   other?

In NumPy, both np.mean() and np.average() are used to compute the central tendency of data, but they have some key differences in their functionality and usage. 

np.mean()-

Purpose: np.mean() calculates the arithmetic mean (average) of the elements along the specified axis of an array.
Basic Usage:
By default, it computes the mean of all elements in the array.
You can specify an axis to compute the mean along that axis.
Syntax: np.mean(array, axis=None, dtype=None, out=None, keepdims=False)
Weights: np.mean() does not take weights into account; it treats all elements equally.

Example:

import numpy as np
data = np.array([1, 2, 3, 4])
mean_value = np.mean(data)  # Output: 2.5

np.average()-

Purpose: np.average() computes the weighted average of the elements along the specified axis of an array.
Basic Usage:
If no weights are provided, np.average() behaves like np.mean().
When weights are provided, it computes the weighted average, which is useful when certain data points contribute more to the average than others.
Syntax: np.average(array, axis=None, weights=None, returned=False)
Weights:
You can pass a weights parameter, which is an array of the same shape as the data (or broadcastable to the same shape). The weighted average is then computed as the sum of the product of the elements and their corresponding weights, divided by the sum of the weights.
If returned=True, the function also returns the sum of the weights along with the weighted average.

Example:

import numpy as np
data = np.array([1, 2, 3, 4])
weights = np.array([0.1, 0.2, 0.3, 0.4])
weighted_avg = np.average(data, weights=weights)  # Output: 3.0

When to Use One Over the Other-

Use np.mean():

When you need the arithmetic mean and do not require weighting.
When you want a simpler and more straightforward calculation.
Use np.average():

When the data points have different importance, and you need to compute a weighted average.
When you need to handle special cases where the sum of weights or additional information is required.

3.  3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D 
    arrays.

Reversing a NumPy array involves flipping the order of elements along a specified axis. Here’s how you can reverse arrays along different axes, with examples for both 1D and 2D arrays:

Reversing a 1D Array-

A 1D array is a simple one-dimensional array. To reverse it, you can use slicing.

Method: Slicing ([::-1])
Syntax: array[::-1]
This uses Python’s slicing feature, where [::-1] reverses the array by stepping backwards.

Example:

import numpy as np

# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Reverse the array
reversed_1d = arr_1d[::-1]

print(reversed_1d)

Output:

[5 4 3 2 1]
Reversing a 2D Array-

A 2D array is a matrix-like structure with rows and columns. You can reverse it along different axes:

Method 1: Reverse Along Rows (Axis 0)-

Syntax: array[::-1, :]
This reverses the order of rows, flipping the array upside down.

Example:

import numpy as np

# 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Reverse along rows (axis 0)
reversed_rows = arr_2d[::-1, :]

print(reversed_rows)

Output:

[[7 8 9]
 [4 5 6]
 [1 2 3]]
 
Method 2: Reverse Along Columns (Axis 1)-

Syntax: array[:, ::-1]
This reverses the order of columns, flipping the array left to right.

Example:

import numpy as np

# Reverse along columns (axis 1)
reversed_columns = arr_2d[:, ::-1]

print(reversed_columns)
Output:

[[3 2 1]
 [6 5 4]
 [9 8 7]]
Method 3: Reverse Along Both Axes-

Syntax: array[::-1, ::-1]
This reverses the array along both rows and columns, effectively rotating it 180 degrees.

Example:

import numpy as np

# Reverse along both axes
reversed_both = arr_2d[::-1, ::-1]

print(reversed_both)
Output:

[[9 8 7]
 [6 5 4]
 [3 2 1]]

4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types 
   in memory management and performance.

Determining the Data Type of Elements in a NumPy Array-

In NumPy, the data type of elements in an array is stored as a dtype object. You can determine the data type of elements in a NumPy array using the .dtype attribute. Here's how you can do it:

Example:

import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3])

# Determine the data type of elements
data_type = arr.dtype

print(data_type)
Output:

int64
In this example, the array contains integers of type int64. The .dtype attribute returns the data type object describing the type of the elements in the array.

Importance of Data Types in Memory Management and Performance-

1. Memory Efficiency
Size of Data Types: Different data types consume different amounts of memory. For example, an int32 (32-bit integer) occupies 4 bytes of memory, while an int64 (64-bit integer) occupies 8 bytes. Choosing the appropriate data type can reduce memory usage significantly, especially when working with large datasets.
Compact Storage: By selecting the smallest appropriate data type for your data, you can optimize the memory footprint of your arrays. For example, if your data consists of values between 0 and 255, you can use uint8 (8-bit unsigned integer) instead of a larger integer type.

2. Performance Optimization
Speed of Computation: Smaller data types generally lead to faster computation because less data needs to be processed by the CPU. For example, operations on float32 arrays can be faster than on float64 arrays because the former requires less computational power.
Cache Efficiency: Smaller data types allow more data to fit in the CPU cache, leading to fewer cache misses and faster access to data during computations.

3. Precision and Range
Precision: The data type determines the precision of numerical operations. For example, float32 provides less precision than float64. If your application requires high precision, such as in scientific calculations, you may need to use a higher precision data type.
Range: Different integer data types have different ranges (e.g., int8 ranges from -128 to 127, while int16 ranges from -32768 to 32767). Choosing a data type with an appropriate range prevents overflow errors and ensures the integrity of your data.

 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

ndarray (n-dimensional array) is the core data structure provided by NumPy. It represents a multidimensional, homogeneous array of fixed-size items, which means that all elements in the array are of the same data type. The ndarray is highly efficient for numerical computations and is the foundation for most of the operations in NumPy.

Key Features of ndarrays-

Multidimensional Structure:

ndarrays can be of any dimension: 1D (like a list), 2D (like a matrix), or higher dimensions (like tensors). The number of dimensions is referred to as the array’s "rank."

Homogeneous Data Type:

All elements in an ndarray must be of the same data type, such as integers, floats, or complex numbers. This uniformity allows NumPy to optimize performance.
You can specify the data type explicitly using the dtype parameter.

Efficient Memory Usage:

ndarrays use contiguous blocks of memory, leading to efficient memory management and fast access. This is in contrast to Python lists, which are arrays of pointers to objects.
The memory layout of ndarrays allows for vectorized operations and makes computations much faster.

Vectorized Operations:

Operations on ndarrays are typically vectorized, meaning they operate on entire arrays at once rather than requiring explicit loops. This leads to cleaner, more concise code and faster execution.

Broadcasting:

NumPy supports broadcasting, a powerful mechanism that allows arithmetic operations on arrays of different shapes by expanding the smaller array across the larger one.

Indexing and Slicing:

Like Python lists, ndarrays can be indexed and sliced, but they extend this capability to multiple dimensions. You can access and modify parts of the array efficiently.

Differences Between ndarrays and Python Lists-

Homogeneity:

ndarrays: All elements must be of the same data type, allowing for more efficient storage and operations.
Python Lists: Elements can be of different data types, leading to greater flexibility but at the cost of efficiency.
Memory Layout:

ndarrays: Stored in contiguous blocks of memory, leading to efficient data processing and lower memory overhead.
Python Lists: Consist of pointers to objects, leading to non-contiguous memory storage and higher overhead.
Performance:

ndarrays: Operations are vectorized and performed in compiled C code, making them significantly faster for numerical computations.
Python Lists: Operations typically involve interpreted Python loops, making them slower, especially for large datasets.
Dimensionality:

ndarrays: Support for multi-dimensional arrays (1D, 2D, 3D, etc.) and advanced slicing/indexing.
Python Lists: Can be nested to create multi-dimensional structures, but these lack the efficiency and flexibility of ndarrays.
Broadcasting:

ndarrays: Supports broadcasting, which allows for operations on arrays of different shapes without needing to reshape or explicitly repeat elements.
Python Lists: Do not support broadcasting; you need to handle shape differences manually.
Built-in Mathematical Functions:

ndarrays: NumPy provides a rich set of mathematical functions that operate on arrays directly and efficiently.
Python Lists: No built-in support for element-wise mathematical operations; you would need to use loops or list comprehensions.

6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

When dealing with large-scale numerical operations, NumPy arrays offer significant performance benefits over Python lists. These benefits arise from several key factors:

1. Memory Efficiency
Contiguous Memory Allocation: NumPy arrays are stored in contiguous blocks of memory, which allows for better cache performance. In contrast, Python lists are arrays of pointers to Python objects, leading to non-contiguous memory allocation.
Fixed Data Types: NumPy arrays require all elements to be of the same data type, reducing the memory overhead associated with storing type information for each element (as is the case with Python lists).
2. Speed
Optimized C Code: NumPy is implemented in C, enabling it to perform operations at much higher speeds compared to Python's built-in lists, which are implemented in Python.
Vectorization: NumPy supports vectorized operations, allowing for element-wise operations to be executed without explicit loops. This reduces the overhead of interpreted loops in Python and leverages highly optimized C loops instead.
Broadcasting: NumPy allows for operations between arrays of different shapes in a way that avoids many explicit copying and reshaping steps that would be required with Python lists.
3. Built-in Functions
Rich Set of Functions: NumPy provides a wide array of optimized mathematical functions that operate on arrays. These functions are optimized to take full advantage of the underlying hardware, such as SIMD (Single Instruction, Multiple Data) instructions, providing significant speedups.
4. Efficiency in Mathematical Operations
Element-wise Operations: Operations like addition, multiplication, or other mathematical functions are applied element-wise in NumPy without the need for looping. Python lists require loops for such operations, which are slower.
Reduction Operations: Summing an entire array or finding the mean is much faster in NumPy because these operations are implemented in optimized C code. In Python, these operations would require traversing the list in Python bytecode.
5. Memory Views
Views on Data: NumPy allows for creating views on arrays without copying the data, which is efficient for large datasets. In contrast, slicing or copying Python lists creates new lists, which is more memory- and time-intensive.

 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and 
    output.

In NumPy, the vstack() and hstack() functions are used to stack arrays vertically and horizontally, respectively. Let's compare these two functions and provide examples to demonstrate their usage and output.

1. vstack() Function-
The vstack() function stacks arrays vertically, meaning it combines arrays along the first axis (row-wise stacking).

Use Case: When you want to stack arrays one on top of another, increasing the number of rows.
Shape: The resulting array has more rows but the same number of columns as the input arrays.
Example:

import numpy as np

# Create two 1D arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Stack them vertically
result_vstack = np.vstack((array1, array2))

print("vstack result:\n", result_vstack)
Output:

vstack result:
 [[1 2 3]
  [4 5 6]]
Here, array1 and array2 are stacked vertically to form a 2x3 array.

2. hstack() Function-
The hstack() function stacks arrays horizontally, meaning it combines arrays along the second axis (column-wise stacking).

Use Case: When you want to stack arrays side by side, increasing the number of columns.
Shape: The resulting array has more columns but the same number of rows as the input arrays.
Example:

import numpy as np

# Create two 1D arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Stack them horizontally
result_hstack = np.hstack((array1, array2))

print("hstack result:\n", result_hstack)
Output:

hstack result:
 [1 2 3 4 5 6]
Here, array1 and array2 are stacked horizontally to form a 1x6 array.

8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various 
   array dimensions.

In NumPy, the fliplr() and flipud() functions are used to flip arrays along specific axes, but they operate differently. Here's a detailed explanation of these two functions, including their effects on arrays of various dimensions:

1. fliplr() Function-

Purpose: fliplr() flips an array horizontally (i.e., it reverses the order of elements along the columns).

Operation: It flips the array from left to right, meaning the first column becomes the last column, the second column becomes the second-to-last, and so on.

Applicable Arrays: It is primarily used on 2D arrays or higher-dimensional arrays where the second axis (columns) exists. If used on a 1D array, it will result in an error because a 1D array has no columns.

Example with a 2D Array:

import numpy as np

# Create a 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Flip the array horizontally (left to right)
result_fliplr = np.fliplr(array)

print("Original array:\n", array)
print("fliplr result:\n", result_fliplr)
Output:

Original array:
 [[1 2 3]
  [4 5 6]
  [7 8 9]]

fliplr result:
 [[3 2 1]
  [6 5 4]
  [9 8 7]]
Effect: Each row of the array is reversed, but the order of the rows remains unchanged.

2. flipud() Function-
Purpose: flipud() flips an array vertically (i.e., it reverses the order of elements along the rows).

Operation: It flips the array from top to bottom, meaning the first row becomes the last row, the second row becomes the second-to-last, and so on.

Applicable Arrays: It is primarily used on 2D arrays or higher-dimensional arrays where the first axis (rows) exists. Unlike fliplr(), flipud() can also be applied to 1D arrays, effectively reversing the array.

Example with a 2D Array:

import numpy as np

# Create a 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Flip the array vertically (top to bottom)
result_flipud = np.flipud(array)

print("Original array:\n", array)
print("flipud result:\n", result_flipud)
Output:

Original array:
 [[1 2 3]
  [4 5 6]
  [7 8 9]]

flipud result:
 [[7 8 9]
  [4 5 6]
  [1 2 3]]
Effect: The rows of the array are reversed, but the order of the columns remains unchanged.

Effect on Higher-Dimensional Arrays-

For arrays with more than two dimensions (e.g., 3D arrays), fliplr() and flipud() still operate along the second and first axes, respectively, but their effects are only observed within each 2D slice of the higher-dimensional array.

 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits

The array_split() method in NumPy is used to split an array into multiple sub-arrays. It is particularly useful when you need to divide an array into a specific number of chunks, especially when the array cannot be evenly divided.

Functionality of array_split()-

Purpose: array_split() splits an array into a specified number of sub-arrays.
Syntax:
numpy.array_split(array, indices_or_sections, axis=0)
array: The input array to be split.
indices_or_sections: Can be either an integer or a list/array of indices.
If an integer is provided, it specifies the number of equal (or nearly equal) sub-arrays to create.
If a list or array of indices is provided, it defines where to split the array.
axis: The axis along which to split the array (default is 0, i.e., row-wise).

Handling Uneven Splits-

When the array cannot be split evenly into the specified number of sections, array_split() handles it by distributing the elements as evenly as possible. Sub-arrays towards the beginning will have one more element than those towards the end if the array size isn't perfectly divisible by the number of sections.

Example 1: Uneven Split with an Integer

Suppose you have an array of 7 elements, and you want to split it into 3 sub-arrays:

import numpy as np

# Create an array of 7 elements
array = np.array([1, 2, 3, 4, 5, 6, 7])

# Split the array into 3 parts
result = np.array_split(array, 3)

print("Original array:", array)
print("Result of array_split into 3 parts:", result)
Output:

Original array: [1 2 3 4 5 6 7]
Result of array_split into 3 parts: [array([1, 2, 3]), array([4, 5]), array([6, 7])]
Here, the first sub-array contains 3 elements, while the other two contain 2 elements each.

Example 2: Split Using Indices

You can also specify the exact indices where the splits should occur:

import numpy as np

# Create an array of 7 elements
array = np.array([1, 2, 3, 4, 5, 6, 7])

# Split the array at the 2nd and 5th positions
result = np.array_split(array, [2, 5])

print("Original array:", array)
print("Result of array_split using indices:", result)
Output:

Original array: [1 2 3 4 5 6 7]
Result of array_split using indices: [array([1, 2]), array([3, 4, 5]), array([6, 7])]
The array is split into three sub-arrays at the specified indices: [2] and [5]

10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array 
    operations?

Vectorization and broadcasting are two fundamental concepts in NumPy that contribute to efficient array operations by leveraging the power of array-based computations without the need for explicit loops. These concepts are essential for achieving high performance in numerical and scientific computing.

1. Vectorization-

Concept
Vectorization refers to the process of performing operations on entire arrays (or large blocks of data) at once, rather than iterating over individual elements using loops. In NumPy, vectorized operations are implemented as optimized, low-level C functions, which allow them to execute much faster than equivalent operations written in pure Python.

How It Works
Element-wise Operations: NumPy allows you to perform operations like addition, subtraction, multiplication, and division directly on entire arrays, applying the operation element-wise without the need for explicit loops.
Vectorized Functions: Many of NumPy's functions are vectorized, meaning they can take arrays as inputs and apply the function to each element of the array simultaneously.
Example of Vectorization:

import numpy as np

# Create two arrays
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

# Element-wise addition (vectorized operation)
result = array1 + array2

print("Result of vectorized addition:", result)
Output:

Result of vectorized addition: [ 6  8 10 12]
Here, the addition operation is applied to the entire arrays at once, rather than element by element using a loop.

2. Broadcasting-

Concept
Broadcasting is a powerful feature in NumPy that allows you to perform arithmetic operations on arrays of different shapes in a way that avoids making unnecessary copies of data. It automatically expands the smaller array to match the shape of the larger array without actually copying the data, enabling element-wise operations between arrays of different sizes.

How It Works
Rules of Broadcasting:
If the arrays have different numbers of dimensions, the shape of the smaller array is padded with ones on its left side (higher dimensions) until it matches the number of dimensions of the larger array.
The arrays are then compared element-wise, starting from the last dimension. Two dimensions are compatible if they are equal or if one of them is 1.
If the dimensions are compatible, NumPy broadcasts the smaller array across the larger one to match its shape.
Example of Broadcasting:

import numpy as np

# Create a 1D array and a 2D array
array1 = np.array([1, 2, 3])
array2 = np.array([[10], [20], [30]])

# Broadcasted addition
result = array1 + array2

print("Result of broadcasting addition:\n", result)
Output:

Result of broadcasting addition:
 [[11 12 13]
  [21 22 23]
  [31 32 33]]
In this example, array1 is a 1D array of shape (3,), and array2 is a 2D array of shape (3, 1). Broadcasting expands array1 to match the shape of array2, resulting in a 3x3 array where each row is the sum of the corresponding element in array2 and all elements in array1.

Contributions to Efficient Array Operations-

Speed: Both vectorization and broadcasting allow NumPy to perform operations using highly optimized, low-level code. This results in significant speedups compared to traditional loop-based approaches in Python.
Memory Usage: Broadcasting avoids unnecessary memory allocation, which reduces overhead and improves performance, especially when working with large datasets.
Code Simplicity: The combination of vectorization and broadcasting leads to cleaner, more readable, and maintainable code. Complex operations can be expressed in a few lines without the need for verbose loops.

PRACTICAL QUES-

1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [1]:
import numpy as np

In [8]:
arr = np.random.randint(1,100,size = (3,3))

In [9]:
arr

array([[19, 24, 53],
       [63, 80, 19],
       [ 9, 36, 22]])

In [10]:
arr.T                       #interchange rows and columns through transpose

array([[19, 63,  9],
       [24, 80, 36],
       [53, 19, 22]])

 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

In [17]:
arr1 = np.random.randint(1,20,(10*1))

In [18]:
arr1

array([12,  2,  9, 15,  7,  9, 16, 14, 14, 16])

In [19]:
#reshaping into 2*5 array
arr1.reshape(2*5)

array([12,  2,  9, 15,  7,  9, 16, 14, 14, 16])

In [21]:
#reshaping into 5*2 array
arr1.reshape(5*2)

array([12,  2,  9, 15,  7,  9, 16, 14, 14, 16])

3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [26]:
arr3 = np.random.uniform(1,30,(4,4))

In [27]:
arr3

array([[21.04222228,  2.13100743, 17.79779001, 19.75586563],
       [18.11429832, 17.54763183,  1.43479691, 27.24456583],
       [21.22064973,  8.44062703, 19.01948973,  6.87123608],
       [20.84086987, 14.0682181 , 12.18058569, 25.41420521]])

In [28]:
 upd_arr3 = np.pad(arr3, pad_width = 1, mode ='constant', constant_values=0)

In [29]:
upd_arr3

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        , 21.04222228,  2.13100743, 17.79779001, 19.75586563,
         0.        ],
       [ 0.        , 18.11429832, 17.54763183,  1.43479691, 27.24456583,
         0.        ],
       [ 0.        , 21.22064973,  8.44062703, 19.01948973,  6.87123608,
         0.        ],
       [ 0.        , 20.84086987, 14.0682181 , 12.18058569, 25.41420521,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ]])

In [30]:
upd_arr3.shape

(6, 6)

4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [3]:
import numpy as np
arr4 = np.arange(10,65,5)              #65 is the stop point so that 60 can be included

In [4]:
arr4

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations 
   (uppercase, lowercase, title case, etc.) to each element.

In [5]:
arr5 = np.array(['python', 'numpy', 'pandas'])

In [6]:
arr5

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [7]:
np.char.upper(arr5)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [8]:
np.char.lower(arr5)

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [9]:
np.char.capitalize(arr5)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [10]:
np.char.title(arr5)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [13]:
arr6 = np.array(["Hello", "world!"])

In [14]:
arr6

array(['Hello', 'world!'], dtype='<U6')

In [15]:
np.char.join(" ",arr6)

array(['H e l l o', 'w o r l d !'], dtype='<U11')

7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [21]:
arr7 = np.random.randint(1,20,(5,6))
arr8 = np.random.randint(20,40,(5,6))

In [17]:
arr7

array([[11,  2,  5,  2,  5,  3],
       [ 5, 16,  5,  6, 19, 19],
       [10, 16, 13,  5,  2,  5],
       [12, 11, 13, 17, 15,  8],
       [15,  1, 19, 13,  2,  5]])

In [22]:
arr8

array([[29, 25, 37, 24, 20, 23],
       [28, 20, 38, 35, 25, 30],
       [39, 27, 24, 29, 30, 32],
       [35, 32, 22, 24, 24, 22],
       [32, 31, 20, 31, 38, 20]])

In [23]:
#addition
arr7 + arr8

array([[31, 30, 54, 37, 30, 33],
       [44, 30, 56, 47, 41, 48],
       [56, 34, 38, 46, 38, 41],
       [48, 49, 39, 40, 27, 24],
       [38, 37, 36, 50, 39, 28]])

In [24]:
#subtraction
arr7 - arr8

array([[-27, -20, -20, -11, -10, -13],
       [-12, -10, -20, -23,  -9, -12],
       [-22, -20, -10, -12, -22, -23],
       [-22, -15,  -5,  -8, -21, -20],
       [-26, -25,  -4, -12, -37, -12]])

In [25]:
#multiplication
arr7*arr8

array([[ 58, 125, 629, 312, 200, 230],
       [448, 200, 684, 420, 400, 540],
       [663, 189, 336, 493, 240, 288],
       [455, 544, 374, 384,  72,  44],
       [192, 186, 320, 589,  38, 160]])

In [26]:
#division
arr7/arr8

array([[0.06896552, 0.2       , 0.45945946, 0.54166667, 0.5       ,
        0.43478261],
       [0.57142857, 0.5       , 0.47368421, 0.34285714, 0.64      ,
        0.6       ],
       [0.43589744, 0.25925926, 0.58333333, 0.5862069 , 0.26666667,
        0.28125   ],
       [0.37142857, 0.53125   , 0.77272727, 0.66666667, 0.125     ,
        0.09090909],
       [0.1875    , 0.19354839, 0.8       , 0.61290323, 0.02631579,
        0.4       ]])

8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [30]:
arr9 = np.eye(5)             #it creates 2 D identity matrix of 5*5

In [31]:
arr9

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
#diagonal() helps in extracting diagonal elements
np.diag(arr9)

array([1., 1., 1., 1., 1.])

9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [42]:
# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
arr10 = np.random.randint(0, 1000, 100)

# Find all prime numbers in the array
prime_numbers = np.array([x for x in arr10 if is_prime(x)])

In [43]:
arr10

array([156, 123, 542, 870, 919, 578, 797, 606, 181, 439, 415, 276, 188,
       718,  12, 818, 372, 100, 287, 755, 743, 557, 274, 370, 723, 314,
       940, 964, 813, 515, 407, 233, 918, 784, 604, 404, 350, 682, 533,
       794, 518, 810, 185, 307, 442,  17, 205, 354, 933, 229, 536, 287,
       583, 677,  39, 164, 457, 181, 138,  47, 770, 609, 541,  45,   0,
       304, 619, 478, 289, 947, 406, 345, 374,  28, 200, 120, 598, 978,
       809, 794,  66, 973, 559,  42, 838, 639, 736, 252, 909,  20, 404,
       311, 591, 261, 137, 397, 586, 926, 357, 727])

In [44]:
prime_numbers

array([919, 797, 181, 439, 743, 557, 233, 307,  17, 229, 677, 457, 181,
        47, 541, 619, 947, 809, 311, 137, 397, 727])

 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly 
averages.

In [45]:
arr11 = np.random.randint(0,40,(6,5))        # assume temperature b/w 0 to 35 degree celsius  for 30 days

In [47]:
arr11

array([[37, 30, 35, 25, 30],
       [29,  5, 17,  8, 19],
       [21, 32, 34, 32, 35],
       [ 9,  1,  0, 18, 18],
       [36,  7, 21, 15, 17],
       [ 2, 33,  7, 11, 13]])

In [49]:
np.mean(arr11, axis = 1)       #weekly average for 5weeks

array([31.4, 15.6, 30.8,  9.2, 19.2, 13.2])